In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import KFold, cross_val_score
from sklearn.linear_model import LinearRegression,Ridge
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler, OrdinalEncoder
from sklearn.compose import ColumnTransformer
import category_encoders as ce

from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error

from sklearn.decomposition import PCA

In [3]:
import warnings
warnings.filterwarnings('ignore')

In [4]:
df = pd.read_csv(r"C:\Users\puruc\Downloads\House Price Prediction\STEP - 3 (Feature Engg)\gurgaon_properties_post_feature_selection.csv").drop(columns=['floor_category','balcony'])

In [5]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,super_built_up_area,servant room,furnishing_type,luxury_category
0,flat,sector 47,2.40,3,3,Moderately Old,2992.86,No,semifurnished,Low
1,flat,sector 65,2.36,3,3,Relatively New,1650.00,Yes,semifurnished,Medium
2,flat,sector 111,2.25,3,3,Relatively New,1700.05,No,unfurnished,Medium
3,flat,sector 71,0.60,2,2,Relatively New,599.98,No,unfurnished,Medium
4,flat,sector 2,1.40,3,3,Moderately Old,1780.03,No,unfurnished,Medium

In [6]:
# Numerical = bedRoom, bathroom, super_built_up_area, servant room
# Ordinal = property_type, furnishing_type, luxury_category 
# OHE = sector, agePossession

#### `1.` Property Type

In [7]:
df['property_type'] = df['property_type'].replace({'flat':0,'house':1})

#### `2.` Age Possession

In [8]:
df['agePossession'] = df['agePossession'].replace(
    {
        'Relatively New':'new',
        'Moderately Old':'old',
        'New Property' : 'new',
        'Old Property' : 'old',
        'Under Construction' : 'under construction'
    }
)

#### `3.` Servant Room

In [9]:
df['servant room'] = df['servant room'].replace({'No':0,'Yes':1})

#### `4.` Furnishing Type

In [10]:
df['furnishing_type'] = df['luxury_category'].replace({'Low':0,'Medium':1,'High':2})

#### `5.` Luxury Category

In [11]:
df['luxury_category'] = df['luxury_category'].replace({'Low':0,'Medium':1,'High':2})

In [12]:
df.head()

,property_type,sector,price,bedRoom,bathroom,agePossession,super_built_up_area,servant room,furnishing_type,luxury_category
0,0,sector 47,2.40,3,3,old,2992.86,0,0,0
1,0,sector 65,2.36,3,3,new,1650.00,1,1,1
2,0,sector 111,2.25,3,3,new,1700.05,0,1,1
3,0,sector 71,0.60,2,2,new,599.98,0,1,1
4,0,sector 2,1.40,3,3,old,1780.03,0,1,1

#### `6` Age Possesion and sector

In [13]:
new_df = pd.get_dummies(df,columns=['sector','agePossession'],drop_first=True)

In [14]:
X = new_df.drop(columns=['price'])
y = new_df['price']

In [15]:
y_log = np.log1p(y)

In [17]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [18]:
X_scaled = pd.DataFrame(X_scaled,columns=X.columns)

In [19]:
X_scaled

,property_type,bedRoom,bathroom,super_built_up_area,servant room,furnishing_type,luxury_category,sector_gwal pahari,sector_manesar,sector_sector 1,...,sector_sector 92,sector_sector 93,sector_sector 95,sector_sector 99,sector_sector 99a,sector_sector 9a,sector_sohna road,sector_sohna road road,agePossession_old,agePossession_under construction
0,-0.505246,-0.125574,-0.171406,0.794932,-0.742617,-0.984739,-0.984739,-0.071786,-0.097407,-0.041374,...,-0.170339,-0.050695,-0.126152,-0.056061,-0.092834,-0.053445,-0.212724,-0.050695,1.676950,-0.29094
1,-0.505246,-0.125574,-0.171406,-0.325787,1.346589,0.437482,0.437482,-0.071786,-0.097407,-0.041374,...,-0.170339,-0.050695,-0.126152,-0.056061,-0.092834,-0.053445,-0.212724,-0.050695,-0.596321,-0.29094
2,-0.505246,-0.125574,-0.171406,-0.284017,-0.742617,0.437482,0.437482,-0.071786,-0.097407,-0.041374,...,-0.170339,-0.050695,-0.126152,-0.056061,-0.092834,-0.053445,-0.212724,-0.050695,-0.596321,-0.29094
3,-0.505246,-0.870318,-0.880246,-1.202109,-0.742617,0.437482,0.437482,-0.071786,-0.097407,-0.041374,...,-0.170339,-0.050695,-0.126152,-0.056061,-0.092834,-0.053445,-0.212724,-0.050695,-0.596321,-0.29094
4,-0.505246,-0.125574,-0.171406,-0.217267,-0.742617,0.437482,0.437482,-0.071786,-0.097407,-0.041374,...,-0.170339,-0.050695,-0.126152,-0.056061,-0.092834,-0.053445,-0.212724,-0.050695,1.676950,-0.29094
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3506,-0.505246,-0.870318,-0.880246,-0.308269,-0.742617,-0.984739,-0.984739,-0.071786,-0.097407,-0.041374,...,-0.170339,-0.050695,-0.126152,-0.056061,-0.092834,-0.053445,-0.212724,-0.050695,-0.596321,-0.29094
3507,-0.505246,-0.125574,-0.171406,-0.006161,-0.742617,-0.984739,-0.984739,-0.071786,-0.097407,-0.041374,...,-0.170339,-0.050695,-0.126152,-0.056061,-0.092834,-0.053445,-0.212724,-0.050695,-0.596321,-0.29094
3508,-0.505246,-0.870318,-0.880246,-0.334141,-0.742617,-0.984739,-0.984739,-0.071786,-0.097407,-0.041374,...,-0.170339,-0.050695,-0.126152,-0.056061,-0.092834,-0.053445,-0.212724,-0.050695,-0.596321,-0.29094
3509,-0.505246,0.619171,0.537434,0.125710,-0.742617,0.437482,0.437482,-0.071786,-0.097407,-0.041374,...,-0.170339,-0.050695,-0.126152,-0.056061,-0.092834,-0.053445,-0.212724,-0.050695,-0.596321,-0.29094
3510,-0.505246,-0.870318,-0.880246,-0.515244,-0.742617,1.859703,1.859703,-0.071786,-0.097407,-0.041374,...,-0.170339,-0.050695,-0.126152,-0.056061,-0.092834,-0.053445,-0.212724,-0.050695,-0.596321,-0.29094

In [20]:
kfold = KFold(n_splits=10, shuffle=True, random_state=42)
scores = cross_val_score(LinearRegression(), X_scaled, y_log, cv=kfold, scoring='r2')

In [21]:
scores.mean(),scores.std()

(0.8523569949240647, 0.01156771860302483)

In [22]:
lr = LinearRegression()
ridge = Ridge(alpha=0.0001)

In [23]:
lr.fit(X_scaled,y_log)

LinearRegression()

In [24]:
ridge.fit(X_scaled,y_log)

Ridge(alpha=0.0001)

In [26]:
lr.coef_.shape

(119,)

In [27]:
coef_df = pd.DataFrame(ridge.coef_.reshape(1,119),columns=X.columns).stack().reset_index().drop(columns=['level_0']).rename(columns={'level_1':'feature',0:'coef'})

In [28]:
coef_df

                              feature      coef
0                       property_type  0.112110
1                             bedRoom  0.013193
2                            bathroom  0.074651
3                 super_built_up_area  0.232203
4                        servant room  0.043067
..                                ...       ...
114                  sector_sector 9a -0.003453
115                 sector_sohna road -0.023850
116            sector_sohna road road -0.010273
117                 agePossession_old -0.014783
118  agePossession_under construction  0.014631

[119 rows x 2 columns]

In [29]:
# 1. Import necessary libraries
import statsmodels.api as sm

# 2. Add a constant to X
X_with_const = sm.add_constant(X_scaled)

# 3. Fit the model
model = sm.OLS(y_log, X_with_const).fit()

# 4. Obtain summary statistics
print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.866
Model:                            OLS   Adj. R-squared:                  0.861
Method:                 Least Squares   F-statistic:                     186.0
Date:                Wed, 25 Sep 2024   Prob (F-statistic):               0.00
Time:                        14:49:48   Log-Likelihood:                 688.20
No. Observations:                3511   AIC:                            -1138.
Df Residuals:                    3392   BIC:                            -404.9
Df Model:                         118
Covariance Type:            nonrobust
=====================================================================================================
                                        coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------------------
const                                 1.0306      0.003    301.773      0.000       1.024       1.037
property_type                         0.1121      0.005     21.123      0.000       0.102       0.123
bedRoom                               0.0132      0.008      1.716      0.086      -0.002       0.028
bathroom                              0.0747      0.008      9.249      0.000       0.059       0.090
super_built_up_area                   0.2322      0.005     46.289      0.000       0.222       0.242
servant room                          0.0431      0.005      9.564      0.000       0.034       0.052
furnishing_type                       0.0032      0.002      1.654      0.098      -0.001       0.007
luxury_category                       0.0032      0.002      1.654      0.098      -0.001       0.007
sector_gwal pahari                    0.0083      0.006      1.346      0.178      -0.004       0.020
sector_manesar                       -0.0261      0.008     -3.356      0.001      -0.041      -0.011
sector_sector 1                      -0.0040      0.005     -0.874      0.382      -0.013       0.005
sector_sector 102                     0.0284      0.013      2.207      0.027       0.003       0.054
sector_sector 103                    -0.0025      0.009     -0.293      0.770      -0.019       0.014
sector_sector 104                     0.0012      0.011      0.110      0.912      -0.019       0.022
sector_sector 105                    -0.0153      0.006     -2.355      0.019      -0.028      -0.003
sector_sector 106                    -0.0021      0.008     -0.252      0.801      -0.018       0.014
sector_sector 107                    -0.0110      0.010     -1.115      0.265      -0.030       0.008
sector_sector 108                     0.0173      0.010      1.759      0.079      -0.002       0.037
sector_sector 109                     0.0252      0.012      2.153      0.031       0.002       0.048
sector_sector 10a                     0.0061      0.005      1.306      0.192      -0.003       0.015
sector_sector 11                     -0.0113      0.006     -1.836      0.066      -0.023       0.001
sector_sector 110                     0.0090      0.007      1.329      0.184      -0.004       0.022
sector_sector 111                     0.0168      0.007      2.539      0.011       0.004       0.030
sector_sector 112                     0.0253      0.007      3.785      0.000       0.012       0.038
sector_sector 113                     0.0327      0.009      3.794      0.000       0.016       0.050
sector_sector 12                     -0.0141      0.008     -1.875      0.061      -0.029       0.001
sector_sector 13                     -0.0139      0.005     -2.933      0.003      -0.023      -0.005
sector_sector 14                      0.0310      0.006      4.965      0.000       0.019       0.043
sector_sector 15                      0.0049      0.005      1.083      0.279      -0.004       0.014
sector_sector 17                     -0.0015      0.005     -0.309      0.758      -0.011       0.008
sector_sector 17b                     0.0102      0.004      2.655      0.008       0.003       0.018
sector_sector 2                       0.0095      0.010      0.949      0.343      -0.010       0.029
sector_sector 21                     -0.0082      0.005     -1.802      0.072      -0.017       0.001
sector_sector 22                      0.0367      0.006      5.727      0.000       0.024       0.049
sector_sector 23                      0.0097      0.005      1.870      0.062      -0.000       0.020
sector_sector 24                      0.0175      0.006      2.822      0.005       0.005       0.030
sector_sector 25                      0.0659      0.008      8.298      0.000       0.050       0.081
sector_sector 26                      0.0825      0.008      9.929      0.000       0.066       0.099
sector_sector 27                      0.0098      0.004      2.557      0.011       0.002       0.017
sector_sector 28                      0.0445      0.008      5.396      0.000       0.028       0.061
sector_sector 3                      -0.0108      0.007     -1.597      0.110      -0.024       0.002
sector_sector 3 phase 2              -0.0113      0.005     -2.336      0.020      -0.021      -0.002
sector_sector 3 phase 3 extension    -0.0165      0.005     -3.181      0.001      -0.027      -0.006
sector_sector 30                      0.0083      0.004      1.897      0.058      -0.000       0.017
sector_sector 31                      0.0256      0.005      4.937      0.000       0.015       0.036
sector_sector 33                      0.0233      0.010      2.271      0.023       0.003       0.043
sector_sector 36                     -0.0051      0.005     -0.963      0.336      -0.015       0.005
sector_sector 36a                     0.0108      0.005      2.050      0.040       0.000       0.021
sector_sector 37c                    -0.0103      0.009     -1.116      0.264      -0.028       0.008
sector_sector 37d                     0.0042      0.010      0.412      0.681      -0.016       0.024
sector_sector 38                      0.0106      0.005      2.050      0.040       0.000       0.021
sector_sector 39                      0.0038      0.005      0.723      0.470      -0.007       0.014
sector_sector 4                      -0.0195      0.008     -2.301      0.021      -0.036      -0.003
sector_sector 40                      0.0118      0.004      2.696      0.007       0.003       0.020
sector_sector 41                      0.0204      0.005      3.825      0.000       0.010       0.031
sector_sector 43                      0.0634      0.010      6.531      0.000       0.044       0.082
sector_sector 45                      0.0271      0.005      5.560      0.000       0.018       0.037
sector_sector 46                      0.0210      0.005      3.938      0.000       0.011       0.031
sector_sector 47                      0.0144      0.006      2.416      0.016       0.003       0.026
sector_sector 48                      0.0541      0.010      5.686      0.000       0.035       0.073
sector_sector 49                      0.0351      0.009      4.012      0.000       0.018       0.052
sector_sector 5                      -0.0004      0.005     -0.095      0.924      -0.009       0.009
sector_sector 50                      0.0720      0.010      7.374      0.000       0.053       0.091
sector_sector 51                      0.0013      0.005      0.282      0.778      -0.008       0.011
sector_sector 52                      0.0058      0.006      1.049      0.294      -0.005       0.017
sector_sector 53                      0.0478      0.006      8.418      0.000       0.037       0.059
sector_sector 54                      0.0443      0.007      6.531      0.000       0.031       0.058
sector_sector 55                      0.0158      0.005      3.142      0.002       0.006       0.026
sector_sector 56                      0.0162      0.009      1.722      0.085      -0.002       0.035
sector_sector 57                      0.0246      0.007      3.732      0.000       0.012       0.038
sector_sector 58                      0.0247      0.005      5.260      0.000       0.015       0.034
sector_sector 59                      0.0303      0.005      6.264      0.000       0.021       0.040
sector_sector 6                      -0.0147      0.005     -2.697      0.007      -0.025      -0.004
sector_sector 60                      0.0261      0.006      4.572      0.000       0.015       0.037
sector_sector 61                      0.0377      0.008      4.478      0.000       0.021       0.054
sector_sector 62                      0.0409      0.006      6.877      0.000       0.029       0.053
sector_sector 63                      0.0352      0.006      6.185      0.000       0.024       0.046
sector_sector 63a                     0.0235      0.006      4.062      0.000       0.012       0.035
sector_sector 65                      0.0756      0.012      6.491      0.000       0.053       0.098
sector_sector 66                      0.0547      0.008      6.436      0.000       0.038       0.071
sector_sector 67                      0.0427      0.009      4.797      0.000       0.025       0.060
sector_sector 67a                     0.0093      0.007      1.426      0.154      -0.003       0.022
sector_sector 68                      0.0122      0.007      1.632      0.103      -0.002       0.027
sector_sector 69                      0.0223      0.012      1.844      0.065      -0.001       0.046
sector_sector 7                      -0.0060      0.008     -0.721      0.471      -0.022       0.010
sector_sector 70                      0.0051      0.009      0.557      0.578      -0.013       0.023
sector_sector 70a                     0.0191      0.010      2.005      0.045       0.000       0.038
sector_sector 71                     -0.0004      0.007     -0.058      0.954      -0.015       0.014
sector_sector 72                      0.0306      0.007      4.143      0.000       0.016       0.045
sector_sector 73                     -0.0033      0.004     -0.811      0.417      -0.011       0.005
sector_sector 74                      0.0227      0.006      3.660      0.000       0.011       0.035
sector_sector 76                      0.0002      0.006      0.036      0.971      -0.011       0.012
sector_sector 77                      0.0023      0.007      0.321      0.748      -0.012       0.016
sector_sector 78                     -0.0026      0.006     -0.431      0.667      -0.014       0.009
sector_sector 79                      0.0124      0.011      1.126      0.260      -0.009       0.034
sector_sector 8                      -0.0127      0.005     -2.592      0.010      -0.022      -0.003
sector_sector 80                      0.0001      0.004      0.029      0.977      -0.008       0.009
sector_sector 81                      0.0174      0.012      1.485      0.138      -0.006       0.040
sector_sector 82                      0.0014      0.008      0.171      0.864      -0.015       0.018
sector_sector 82a                     0.0112      0.006      1.779      0.075      -0.001       0.024
sector_sector 83                      0.0012      0.011      0.114      0.909      -0.019       0.022
sector_sector 84                     -0.0085      0.009     -0.928      0.354      -0.026       0.009
sector_sector 85                      0.0064      0.013      0.495      0.620      -0.019       0.032
sector_sector 86                     -0.0010      0.010     -0.102      0.919      -0.021       0.019
sector_sector 88a                     0.0067      0.007      1.030      0.303      -0.006       0.020
sector_sector 88b                     0.0001      0.004      0.028      0.977      -0.008       0.008
sector_sector 89                      0.0038      0.010      0.388      0.698      -0.015       0.023
sector_sector 9                      -0.0117      0.005     -2.139      0.032      -0.022      -0.001
sector_sector 90                     -0.0097      0.012     -0.817      0.414      -0.033       0.014
sector_sector 91                      0.0007      0.006      0.119      0.905      -0.011       0.013
sector_sector 92                     -0.0236      0.012     -1.906      0.057      -0.048       0.001
sector_sector 93                     -0.0032      0.005     -0.636      0.525      -0.013       0.007
sector_sector 95                     -0.0235      0.010     -2.445      0.015      -0.042      -0.005
sector_sector 99                      0.0012      0.005      0.223      0.824      -0.009       0.012
sector_sector 99a                    -0.0118      0.007     -1.584      0.113      -0.026       0.003
sector_sector 9a                     -0.0035      0.005     -0.669      0.503      -0.014       0.007
sector_sohna road                    -0.0238      0.015     -1.583      0.114      -0.053       0.006
sector_sohna road road               -0.0103      0.005     -2.054      0.040      -0.020      -0.000
agePossession_old                    -0.0148      0.005     -3.020      0.003      -0.024      -0.005
agePossession_under construction      0.0146      0.004      3.709      0.000       0.007       0.022
==============================================================================
Omnibus:                      470.555   Durbin-Watson:                   2.010
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4007.574
Skew:                          -0.348   Prob(JB):                         0.00
Kurtosis:                       8.188   Cond. No.                     1.42e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 6.14e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

stand_coef = unstand_coef * {(std x)/(std y)}

In [39]:
stand_coef = 0.0132
std_x = X['bedRoom'].std()
std_y = y_log.std()

In [40]:
unstand_coef = (stand_coef * std_y)/std_x

In [41]:
unstand_coef

0.005344439938446593

In [43]:
np.expm1(0.005344439938446593)

0.005358746933844827